# Realtime blocklists. Effective only when DNS goes through Unbound (see
# options.inc) - public resolvers are rate-limited by Spamhaus.
rbls {
    spamhaus_zen {
        symbol = "RBL_SPAMHAUS_ZEN";
        rbl = "zen.spamhaus.org";
        ipv4 = true;
        ipv6 = false;
        from = true;
        received = true;
    }
    abusix_mail {
        symbol = "RBL_ABUSIX";
        rbl = "combined.mail.abusix.zone";
        ipv4 = true;
        from = true;
        received = true;
    }
    spamcop {
        symbol = "RBL_SPAMCOP";
        rbl = "bl.spamcop.net";
        ipv4 = true;
        from = true;
        received = true;
    }
}
